# Generated by Django 2.2.4 on 2021-08-28 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='user_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_user', to='users.Users'),
        ),
    ]
